[package]
name = "nomad"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "15.0.0"
clap = "2.33.3"
gc = { version = "0.4", features = ["derive"] }
